version: "3.8"
services:
  familjen_scoreboard:
    image: familjen-scoreboard
    build: .
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=
      - SQLALCHEMY_DATABASE_URI=
      - SCOREBOARD_EMAIL_SENDER=
      - SCOREBOARD_SMTP_HOST=
      - SCOREBOARD_SMTP_PORT=
      - SCOREBOARD_SMTP_USERNAME=
      - SCOREBOARD_SMTP_PASSWORD=
      - SCOREBOARD_ADMIN_USER_EMAIL=
      - SCOREBOARD_ADMIN_USER_NAME=
      - SCOREBOARD_ADMIN_USER_PASSWORD=
      - LOGGING_LEVEL=30
      - PYTHONUNBUFFERED=1
